language: csharp
solution: MigrationRunner.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore MigrationRunner.sln
after_script:
  - nunit-console libs/MigrationRunner.Test/bin/Debug/MigrationRunner.Test.dll